export const ADD_IT_RESPONSABLE = "ADD_IT_RESPONSABLE";
export const GET_IT_RESPONSABLES = "GET_IT_RESPONSABLES";
export const UPDATE_IT_RESPONSABLE = "UPDATE_IT_RESPONSABLE";
export const DELETE_IT_RESPONSABLE = "DELETE_IT_RESPONSABLE";