export const ADD_PROJECT = "ADD_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const ADD_API_TO_PROJECT = "ADD_API_TO_PROJECT";
export const REMOVE_API_FROM_PROJECT = "REMOVE_API_FROM_PROJECT";
