export const ADD_WORK_RESPONSABLE = "ADD_WORK_RESPONSABLE";
export const GET_WORK_RESPONSABLES = "GET_WORK_RESPONSABLES";
export const UPDATE_WORK_RESPONSABLE = "UPDATE_WORK_RESPONSABLE";
export const DELETE_WORK_RESPONSABLE = "DELETE_WORK_RESPONSABLE";